{% set version = "0.9.37" %}
{% set name = "PyAutoGUI" %}

package:
  name: pyautogui
  version: {{ version }}

source:
  fn: PyAutoGUI-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00c0aec56dd72fb24baf2c0c230ff2d6b6ee3de2591a16eab589912c0f3f32b2

build:
  number: 0
  script:
    # https://github.com/asweigart/pyautogui/pull/197
    - python setup.py install  --single-version-externally-managed --record=record.txt  # [not linux]
    - DISPLAY=localhost:1.0 xvfb-run python setup.py install  --single-version-externally-managed --record=record.txt  # [linux]

requirements:
  build:
    - python
    - setuptools
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]
  run:
    - python
    - pymsgbox
    - pytweening
    - pyscreeze
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]

test:
  imports:
    - pyautogui  # [not linux]
  commands:
    - DISPLAY=localhost:1.0 xvfb-run python -c "import pyautogui"  # [linux]

about:
  home: https://github.com/asweigart/pyautogui
  license: BSD 3-Clause
  license_family: BSD
  # https://github.com/asweigart/pyautogui/pull/196
  #license_file: LICENSE.txt
  summary: A cross-platform module for GUI automation for human beings. Control the keyboard and mouse from a Python script.

extra:
  recipe-maintainers:
    - jschueller
