{% set version = "0.9.40" %}
{% set name = "PyAutoGUI" %}

package:
  name: pyautogui
  version: {{ version }}

source:
  fn: PyAutoGUI-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bc7c03ab5bda9dc97bc60ece4411361e29888af22a78247bb6a1ed8aa058f57

build:
  number: 1000
  script:
    - "{{ PYTHON }} -m pip install . -vv"  # [not linux]
    - DISPLAY=localhost:1.0 xvfb-run {{ PYTHON }} -m pip install . -vv  # [linux]

requirements:
  build:
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
  host:
    - python
    - pip
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]
  run:
    - python
    - pymsgbox
    - pytweening
    - pyscreeze
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]

test:
  imports:
    - pyautogui  # [not linux]
  commands:
    - DISPLAY=localhost:1.0 xvfb-run python -c "import pyautogui"  # [linux]

about:
  home: https://github.com/asweigart/pyautogui
  license: BSD 3-Clause
  license_family: BSD
  # https://github.com/asweigart/pyautogui/pull/196
  #license_file: LICENSE.txt
  summary: A cross-platform module for GUI automation for human beings. Control the keyboard and mouse from a Python script.

extra:
  recipe-maintainers:
    - jschueller
