{% set name = "pyautogui" %}
{% set version = "0.9.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyAutoGUI-{{ version }}.tar.gz
  sha256: dd1d29e8fd118941cb193f74df57e5c6ff8e9253b99c7b04f39cfc69f3ae04b2

build:
  skip: true  # [py<36]
  number: 3
  script:
    - {{ PYTHON }} -m pip install . -vv    # [not linux]
    - "DISPLAY=localhost:1.0 xvfb-run {{ PYTHON }} -m pip install . -vv"  # [linux]

requirements:
  host:
    - pip
    - python
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]
    - setuptools

  run:
    - mouseinfo
    - pygetwindow >=0.0.5  # [not linux]
    - pymsgbox
    - pyobjc-core  # [osx]
    - pyobjc-framework-quartz  # [osx]
    - pyscreeze >=0.1.21
    - python
    - pytweening >=1.0.4
    - python-xlib

test:
# Disabling test suite for now so many of them requires 
  source_files:
    - tests
  imports:
    - pyautogui  # [not linux]
  commands:
    - export DISPLAY=:99  # [linux]
    - xvfb-run python -c "import mouseinfo"  &  # [linux]
#     - pytest -vvv --capture=tee-sys -k "not TestKeyboard and not TestPyScreezeFunctions and not test__normalizeXYArgs" tests  # [win]
#     - pytest -vvv --capture=tee-sys -k "not TestKeyboard and not TestPyScreezeFunctions and not test__normalizeXYArgs and not TestMouse and not TestFailSafe" tests  # [linux]
#     - pytest -vvv --capture=tee-sys -k "not TestKeyboard and not TestPyScreezeFunctions and not test__normalizeXYArgs and not test_pause" tests  # [osx]
  requires:
    - pip
#     - pytest

about:
  home: https://github.com/asweigart/pyautogui
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A cross-platform module for GUI automation for human beings. Control the keyboard and mouse from a Python script.

extra:
  recipe-maintainers:
    - thewchan
    - jschueller
