{% set version = "0.9.53" %}
{% set name = "PyAutoGUI" %}

package:
  name: pyautogui
  version: {{ version }}

source:
  fn: PyAutoGUI-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d31de8f712218d90be7fc98091fce1a12a3e9196e0c814eb9afd73bb2ec97035

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    # - DISPLAY=localhost: 1.0 xvfb-run {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]

  run:
    - python
    - pymsgbox
    - pytweening
    - pyscreeze
    - python-xlib  # [linux]
    - pyobjc-framework-quartz  # [osx]

test:
  imports:
    - pyautogui  # [not linux]
  commands:
    - DISPLAY=localhost: 1.0 xvfb-run python -c "import pyautogui"  # [linux]

about:
  home: https://github.com/asweigart/pyautogui
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A cross-platform module for GUI automation for human beings. Control the keyboard and mouse from a Python script.

extra:
  recipe-maintainers:
    - jschueller
    - thewchan
