appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jdFViYmNm2Z4kyLr6kZU+p/l3mgin4i5TskZNylnKUZ7/HR31nQjKBLl2RKL1AD73O9eOwnNXZ1YlnnGAvZgvQ603uM3NZ9jiPpbhzGoHuMqYGdGYF7gXKxkrw6zc3eiJZe+ASklTZozWlpsk5BcFSNHWA6VGsjpSrLWvFcIoXLdE71bDETzVDpcf9+tS5DZ2BI4i34MJAiLpYBE9m40ZdlC4MWLghdxn3Y2JIiSVpeA36rC/mo4Cf2xjeLBXXNMUHAX/QgGc+nGbBX/Fm+y6GbdrHRcE6cF8U1LLC3srOF4SOEkyoBs+XW4gJ37Nq5RffC9PoUI0bDgBnSqLOT745+Fmk4DBnfHtmRlB2qhyQ9fd/6dMZQIM/phX9uH0myuIHzvVthaiE/x/fMX3BVNtmA7YJOrmoGZjnGc0WBp00LcbNVlUzYwoy5G6gZVT1lFcpeKVGsrGF6CjByn5qqRQPSzy3fjfeUWO0vP9ZjVzWqFNacp42Suw8JQaH4sh7AsRfVePUKmRWFMIr3XktI3q/M1LaPChhvRZ1rTp6/wVPGdebKDKc12ulH/k2A1oyg0W/gV3zPTrEKBZUThqngyM88JWmNraO4bvGmiKoO4fnNcHjbN2kQ2zv+TRdLzQTMaqESAhpNesz0pi8I8PI9YBnTsfUhDMJ6wkBy5obhZeQY=}
provider:
  win: azure
conda_forge_output_validation: true
